### PR TITLE
Fix 70/start service on reboot

### PR DESCRIPTION
**Pull request by hossain-khan**
This pull request includes changes to add support for starting the `WatchdogService` even when the device is locked. The most important changes include updating the permissions in the `README.md` file, modifying the `AndroidManifest.xml` to include the `LOCKED_BOOT_COMPLETED` action, and updating the `BootCompleteReceiver` class to handle the new action and use device-protected storage.

### Permissions Update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L46-R61): Added `android.permission.ACTION_LOCKED_BOOT_COMPLETED` to allow the app to start services even when the device is locked.

### Manifest Changes:
* [`app/src/main/AndroidManifest.xml`](diffhunk://#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdR85-R104): Added `android.intent.action.LOCKED_BOOT_COMPLETED` action to the `BootCompleteReceiver` to handle boot events when the device is locked.

### Broadcast Receiver Update:
* [`app/src/main/java/dev/hossain/keepalive/broadcast/BootCompleteReceiver.kt`](diffhunk://#diff-632c76bc7202bf6becfbdd1e0589e58c704d45e0ae4192ab671184d5baf80f8eL18-R29): Updated `BootCompleteReceiver` to handle the `LOCKED_BOOT_COMPLETED` action and use device-protected storage context to start the `WatchdogService`.

### CODE REVIEW

**Comment by hossain-khan** [comment]
So, after boot completed I am getting this 

```
--------- beginning of system
2024-12-18 23:18:42.234  1429-1429  ssain.keepaliv          dev.hossain.keepalive                I  Late-enabling -Xcheck:jni
2024-12-18 23:18:42.240  1429-1429  ssain.keepaliv          dev.hossain.keepalive                I  Unquickening 12 vdex files!
2024-12-18 23:18:42.384  1429-1429  ContextImpl             dev.hossain.keepalive                W  Failed to ensure /data/user/0/dev.hossain.keepalive/cache: mkdir failed: errno 126 (Required key not available)
2024-12-18 23:18:42.384  1429-1429  ContextImpl             dev.hossain.keepalive                W  Failed to update user.inode_cache: stat failed: ENOENT (No such file or directory)
2024-12-18 23:18:42.387  1429-1429  NetworkSecurityConfig   dev.hossain.keepalive                D  No Network Security Config specified, using platform default
2024-12-18 23:18:42.387  1429-1429  NetworkSecurityConfig   dev.hossain.keepalive                D  No Network Security Config specified, using platform default
2024-12-18 23:18:42.417  1429-1429  KeepAliveApplication    dev.hossain.keepalive                I  KeepAliveApplication.onCreate() completed.
2024-12-18 23:18:42.418  1429-1429  BootCompleteReceiver    dev.hossain.keepalive                D  BootCompleteReceiver onReceive() called with: context = android.app.ReceiverRestrictedContext@fe5b541, intent = Intent { act=android.intent.action.LOCKED_BOOT_COMPLETED flg=0x89000010 cmp=dev.hossain.keepalive/.broadcast.BootCompleteReceiver (has extras) }
2024-12-18 23:18:42.418  1429-1429  BootCompleteReceiver    dev.hossain.keepalive                D  BootCompleteReceiver onReceive: Starting WatchdogService
2024-12-18 23:18:42.418  1429-1479  ContextImpl             dev.hossain.keepalive                W  Failed to ensure /data/user/0/dev.hossain.keepalive/files: mkdir failed: errno 126 (Required key not available)
2024-12-18 23:18:42.423  1429-1476  KeepAliveA...n$onCreate dev.hossain.keepalive                D  Airtable configuration is invalid or not enabled. Disable remote logging.
---------------------------- PROCESS STARTED (1429) for package dev.hossain.keepalive ----------------------------
```

But no start of foreground service until unlocked - which means this change did not work ❌ 

After unlock

```
---------------------------- PROCESS ENDED (1429) for package dev.hossain.keepalive ----------------------------


---------------------------- PROCESS STARTED (4289) for package dev.hossain.keepalive ----------------------------

2024-12-18 23:19:54.808  4289-4289  ssain.keepaliv          dev.hossain.keepalive                W  Accessing hidden method Landroid/content/res/Resources;->overrideDisplayAdjustments(Ljava/util/function/Consumer;)V (blacklist, linking, denied)
2024-12-18 23:19:54.808  4289-4289  ssain.keepaliv          dev.hossain.keepalive                W  Accessing hidden method Landroid/app/ResourcesManager;->updateResourcesForActivity(Landroid/os/IBinder;Landroid/content/res/Configuration;IZ)V (greylist-max-o, linking, denied)
2024-12-18 23:19:54.808  4289-4289  ssain.keepaliv          dev.hossain.keepalive                W  Accessing hidden method Landroid/app/ResourcesManager;->getOrCreateActivityResourcesStructLocked(Landroid/os/IBinder;)Landroid/app/ResourcesManager$ActivityResources; (greylist-max-o, linking, denied)
2024-12-18 23:19:54.808  4289-4289  ssain.keepaliv          dev.hossain.keepalive                W  Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
2024-12-18 23:19:54.808  4289-4289  ssain.keepaliv          dev.hossain.keepalive                W  Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
2024-12-18 23:19:54.993  4289-4289  NetworkSecurityConfig   dev.hossain.keepalive                D  No Network Security Config specified, using platform default
2024-12-18 23:19:54.993  4289-4289  NetworkSecurityConfig   dev.hossain.keepalive                D  No Network Security Config specified, using platform default
2024-12-18 23:19:55.042  4289-4289  KeepAliveApplication    dev.hossain.keepalive                I  KeepAliveApplication.onCreate() completed.
2024-12-18 23:19:55.046  4289-4289  BootCompleteReceiver    dev.hossain.keepalive                D  BootCompleteReceiver onReceive() called with: context = android.app.ReceiverRestrictedContext@9630040, intent = Intent { act=android.intent.action.BOOT_COMPLETED flg=0x89000010 cmp=dev.hossain.keepalive/.broadcast.BootCompleteReceiver (has extras) }
2024-12-18 23:19:55.046  4289-4289  BootCompleteReceiver    dev.hossain.keepalive                D  BootCompleteReceiver onReceive: Starting WatchdogService
2024-12-18 23:19:55.076  4289-4334  KeepAliveA...n$onCreate dev.hossain.keepalive                D  Airtable configuration is invalid or not enabled. Disable remote logging.
2024-12-18 23:19:55.096  4289-4289  WatchdogService         dev.hossain.keepalive                D  onStartCommand() called with: intent = Intent { cmp=dev.hossain.keepalive/.service.WatchdogService }, flags = 0, startId = 1
2024-12-18 23:19:55.096  4289-4289  NotificationHelper      dev.hossain.keepalive                D  createNotificationChannel() called
2024-12-18 23:19:55.099  4289-4289  NotificationHelper      dev.hossain.keepalive                D  buildNotification() called
2024-12-18 23:19:55.117  4289-4289  WatchdogSe...artCommand dev.hossain.keepalive                D  [Start ID: 1] Current time: 1734581995111 @ Wed Dec 18 23:19:55 EST 2024
2024-12-18 23:19:55.128  4289-4289  WatchdogSe...artCommand dev.hossain.keepalive                D  Next check will be done in 10 minutes.
2024-12-18 23:19:56.793  4289-4310  System                  dev.hossain.keepalive                W  A resource failed to call close. 
2024-12-18 23:20:00.586  4289-4580  ProfileInstaller        dev.hossain.keepalive                D  Installing profile for dev.hossain.keepalive
```

**Comment by hossain-khan** [comment]
Closing without merging as #70 can't be fixed.

**Comment by hossain-khan** [comment]
> Try adding `android:directBootAware="true"` to not only `BootCompleteReceiver` but also `WatchdogService`?

I have tried that, you can't start service with direct boot context unfortunately.

https://github.com/hossain-khan/android-keep-alive/blob/eeec0ae99450fda2314d69544b284e9b02ab2aec/app/src/main/java/dev/hossain/keepalive/broadcast/BootCompleteReceiver.kt#L27-L29

**Comment by liweiyap** [comment]
No, I mean that you need to add it to your `AndroidManifest`.

https://github.com/hossain-khan/android-keep-alive/blob/414cf87d2d38c258c6bbf51e06583906162128ef/app/src/main/AndroidManifest.xml#L79-L81

You need to add `android:directBootAware="true"` here.

Otherwise, whether or not your context is device-protected, `Context#startForegroundService` returns `null` on device reboot. In other words, there won't actually be any foreground service running.

**Pull request closed without merging**
